package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/logoscore/logos-core/core/pkg/eventbus"
	"github.com/logoscore/logos-core/core/pkg/graphql/model"
)

// AgentActivity is the resolver for the agentActivity field.
//
// Streams every MCP tool call an agent makes in this operation, reads
// included, so the operator can watch it work rather than only see the
// aftermath. Same bridge pattern as TimelineEventAdded, but without the
// refetch: the payload already carries everything the rail renders, and an
// agent running dozens of tools a minute should not put a database read on
// the hot path.
func (r *subscriptionResolver) AgentActivity(ctx context.Context, operationID string) (<-chan *model.AgentActivityEvent, error) {
	auth, err := subscriberAuth(ctx)
	if err != nil {
		return nil, err
	}
	filter, err := r.buildOperationFilter(ctx, auth, &operationID)
	if err != nil {
		return nil, err
	}
	return stream(ctx, r.EventBus, []eventbus.Topic{eventbus.TopicAgentAction}, filter, pure(agentActivityEvent)), nil
}
