package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/logoscore/logos-core/core/pkg/graphql/generated"
	"github.com/logoscore/logos-core/core/pkg/graphql/model"
	"github.com/logoscore/logos-core/core/pkg/models"
)

// ID is the resolver for the id field.
func (r *hostResolver) ID(ctx context.Context, obj *models.Host) (string, error) {
	return r.HostResolver.ID(ctx, obj)
}

// OperationID is the resolver for the operationId field.
func (r *hostResolver) OperationID(ctx context.Context, obj *models.Host) (string, error) {
	return r.HostResolver.OperationIDField(ctx, obj)
}

// Operation is the resolver for the operation field.
func (r *hostResolver) Operation(ctx context.Context, obj *models.Host) (*models.Operation, error) {
	return r.HostResolver.Operation(ctx, obj)
}

// CreatedBy is the resolver for the createdBy field.
func (r *hostResolver) CreatedBy(ctx context.Context, obj *models.Host) (*models.User, error) {
	return r.HostResolver.CreatedBy(ctx, obj)
}

// CreatedAt is the resolver for the createdAt field.
func (r *hostResolver) CreatedAt(ctx context.Context, obj *models.Host) (string, error) {
	return r.HostResolver.CreatedAt(ctx, obj)
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *hostResolver) UpdatedAt(ctx context.Context, obj *models.Host) (string, error) {
	return r.HostResolver.UpdatedAt(ctx, obj)
}

// CreateHost is the resolver for the createHost field.
func (r *mutationResolver) CreateHost(ctx context.Context, operationID string, input model.CreateHostInput) (*models.Host, error) {
	return r.HostResolver.CreateHost(ctx, operationID, input)
}

// UpdateHost is the resolver for the updateHost field.
func (r *mutationResolver) UpdateHost(ctx context.Context, id string, input model.UpdateHostInput) (*models.Host, error) {
	return r.HostResolver.UpdateHost(ctx, id, input)
}

// DeleteHost is the resolver for the deleteHost field.
func (r *mutationResolver) DeleteHost(ctx context.Context, id string) (bool, error) {
	return r.HostResolver.DeleteHost(ctx, id)
}

// Host is the resolver for the host field.
func (r *queryResolver) Host(ctx context.Context, id string) (*models.Host, error) {
	return r.HostResolver.Host(ctx, id)
}

// Hosts is the resolver for the hosts field.
func (r *queryResolver) Hosts(ctx context.Context, operationID string, search *string, sortBy *model.HostSortField, sortDirection *model.SortDirection, first *int, after *string, last *int, before *string) (*model.HostConnection, error) {
	return r.HostResolver.Hosts(ctx, operationID, search, sortBy, sortDirection, first, after, last, before)
}

// HostChanged is the resolver for the hostChanged field.
//
// Same shape as credentialChanged: subscribe to host events scoped to the given
// operation, fetch the full host for non-delete events, and stream them to the
// client.
func (r *subscriptionResolver) HostChanged(ctx context.Context, operationID string) (<-chan *model.HostEvent, error) {
	auth, err := subscriberAuth(ctx)
	if err != nil {
		return nil, err
	}
	filter, err := r.buildOperationFilter(ctx, auth, &operationID)
	if err != nil {
		return nil, err
	}
	return stream(ctx, r.EventBus, hostTopics, filter, r.hostEvent), nil
}

// Host returns generated.HostResolver implementation.
func (r *Resolver) Host() generated.HostResolver { return &hostResolver{r} }

type hostResolver struct{ *Resolver }
