package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/logoscore/logos-core/core/pkg/eventbus"
	"github.com/logoscore/logos-core/core/pkg/graphql/generated"
	"github.com/logoscore/logos-core/core/pkg/graphql/model"
)

// UserChanged is the resolver for the userChanged field.
//
// It subscribes to user create/update/delete events and streams them to the
// client as SSE frames. Each event includes the action, user ID, username,
// and (for non-DELETE) the full User object fetched from the database.
//
// Channel lifecycle:
//  1. We create a buffered channel and subscribe to the event bus
//  2. The event bus handler converts events and sends them on the channel
//  3. gqlgen reads from the channel and writes SSE frames to the HTTP response
//  4. When the client disconnects, gqlgen cancels ctx — our cleanup goroutine
//     unsubscribes from the event bus and closes the channel
func (r *subscriptionResolver) UserChanged(ctx context.Context) (<-chan *model.UserEvent, error) {
	if _, err := subscriberAuth(ctx); err != nil {
		return nil, err
	}
	topics := []eventbus.Topic{
		eventbus.TopicUserCreated,
		eventbus.TopicUserUpdated,
		eventbus.TopicUserDeleted,
	}
	return stream(ctx, r.EventBus, topics, nil, r.userEvent), nil
}

// OperationChanged is the resolver for the operationChanged field.
//
// If operationID is provided, only events for that operation are delivered.
// Otherwise, events for all operations the caller is a member of are delivered.
// The membership set is captured at subscribe time — if the caller joins a new
// operation, they need to reconnect to receive events for it.
func (r *subscriptionResolver) OperationChanged(ctx context.Context, operationID *string) (<-chan *model.OperationEvent, error) {
	auth, err := subscriberAuth(ctx)
	if err != nil {
		return nil, err
	}
	filter, err := r.buildOperationFilter(ctx, auth, operationID)
	if err != nil {
		return nil, err
	}
	topics := []eventbus.Topic{
		eventbus.TopicOperationCreated,
		eventbus.TopicOperationUpdated,
		eventbus.TopicOperationDeleted,
	}
	return stream(ctx, r.EventBus, topics, filter, r.operationEvent), nil
}

// OperationMemberChanged is the resolver for the operationMemberChanged field.
//
// Same scoping as OperationChanged — provide operationId to filter to one
// operation, or omit to receive events for all the caller's operations.
func (r *subscriptionResolver) OperationMemberChanged(ctx context.Context, operationID *string) (<-chan *model.OperationMemberEvent, error) {
	auth, err := subscriberAuth(ctx)
	if err != nil {
		return nil, err
	}
	filter, err := r.buildOperationFilter(ctx, auth, operationID)
	if err != nil {
		return nil, err
	}
	topics := []eventbus.Topic{
		eventbus.TopicOperationMemberAdded,
		eventbus.TopicOperationMemberRemoved,
		eventbus.TopicOperationMemberUpdated,
	}
	return stream(ctx, r.EventBus, topics, filter, pure(toOperationMemberEvent)), nil
}

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type subscriptionResolver struct{ *Resolver }
